### ISSUE TITLE
Aborted: could not find any git remote pointing to a GitHub repository

### ISSUE THREAD

**Issue by ChristophShyper** [devops-infra/action-pull-request#42]
### Brief description

Pull requests created by Dependabot produce execution errors.

```

Listing new commits in the source branch...
* 624917e - dependabot[bot] - 2021-04-26 11:27:21 
  Bump urllib3 from 1.26.2 to 1.26.4 in /backend Bumps [urllib3](https://github.com/urllib3/urllib3) from 1.26.2 to 1.26.4.
  - [Release notes](https://github.com/urllib3/urllib3/releases)
  - [Changelog](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst)
  - [Commits](https://github.com/urllib3/urllib3/compare/1.26.2...1.26.4)
  
  Signed-off-by: dependabot[bot] <support@github.com>

Listing commits subjects in the source branch...
Bump urllib3 from 1.26.2 to 1.26.4 in /backend

Listing files modified in the source branch...
 backend/requirements.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

Setting template...
Aborted: could not find any git remote pointing to a GitHub repository
```

### Checklist
* [X] Provided a clear and concise description of what the bug is.
* [ ] Given a clear and concise description of what was expected to happen.
* [ ] Provided an information how to reproduce the error.
* [ ] If applicable, added screenshots to help explain the issue.
* [ ] Added any other context about the issue that can help to understand it.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md](../blob/master/.github/CONTRIBUTING.md) for more information*

**Comment by giangpham96** [comment]
I still get this when the actor is a bot. How does ignore_users help in this case @ChristophShyper ?

**Comment by ChristophShyper** [comment]
This shouldn't be run when the user triggering the action is dependabot.
Because dependabot creates pull request first.
By default it should skip it. If you haven't specified any other `ignore_users` value.

**Comment by giangpham96** [comment]
hm, in my case, it's dependabot-preview. It shouldn't be skipped because ignore_users is by default set to dependabot. However, it fails giving an error `Aborted: could not find any git remote pointing to a GitHub repository`

**Comment by ChristophShyper** [comment]
Ok, in other words, if any user - real or a bot - creates the pull request first it should be added to `ignore_users`.
If not then you get this error.

**Comment by giangpham96** [comment]
but ignore_users will prevent pr creation, right?

**Comment by ChristophShyper** [comment]
Yes, but the pull requested is already created by that user, right?

**Comment by giangpham96** [comment]
no, it didn't

**Comment by giangpham96** [comment]
but can you help me understand why the error happen?

**Comment by ChristophShyper** [comment]
It's very hard to help if I don't know anything about your problem. 
What's your workflow? Can you show the logs? etc.

**Comment by giangpham96** [comment]
so I have a branch A.
a bot opens PR from branch B to A, after it's approved, the bot merges PR B to A.
whenever smt is pushed to branch A, a bot create a branch out of A, called C, commit something, and try to open a PR from C to master. That last step fails.

**Comment by ChristophShyper** [comment]
And how is the last workflow checked out?

**Comment by giangpham96** [comment]
last branch & commits to it were done by using `devops-infra/action-commit-push`

**Comment by ChristophShyper** [comment]
But what about checkout?

**Comment by giangpham96** [comment]
ah sorry. Here
```
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 0
```

**Comment by ChristophShyper** [comment]
Maybe start with updating it. Seems like a very old verion.

**Comment by giangpham96** [comment]
ah, I didn't have time to try it 😅
